---
name: Unit Tests
on: [push, pull_request]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - name: Build
        run: go build -v ./...
      - name: Run Tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v
      - name: Publish coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}